export const MSG = {
  STATE: 'state',
  TOAST: 'toast',
  LOADING: 'loading',
  ACTION_RESULT: 'actionResult',
  PWD_RESULT: 'pwdResult',
};

export const ACTION = {
  REQUEST_STATE: 'requestState',
  REMOVE: 'remove',
  LOGIN: 'login',
  BATCH_ADD: 'batchAdd',
  REFRESH: 'refresh',
  REFRESH_ALL_AND_ROTATE: 'refreshAllAndRotate',
  REFRESH_ONE: 'refreshOne',
  SMART_ROTATE: 'smartRotate',
  PANIC_SWITCH: 'panicSwitch',
  SET_MODE: 'setMode',
  REPROBE_PROXY: 'reprobeProxy',
  RESET_FINGERPRINT: 'resetFingerprint',
  RESET_ACCOUNT_FINGERPRINT: 'resetAccountFingerprint',
  REMOVE_EMPTY: 'removeEmpty',
  TOGGLE_DETAIL: 'toggleDetail',
  SET_PROXY_PORT: 'setProxyPort',
  SET_AUTO_ROTATE: 'setAutoRotate',
  SET_PREEMPTIVE_THRESHOLD: 'setPreemptiveThreshold',
  SET_MANUAL_THRESHOLD: 'setManualThreshold',
  EXPORT_ACCOUNTS: 'exportAccounts',
  IMPORT_ACCOUNTS: 'importAccounts',
  CLEAR_RATE_LIMIT: 'clearRateLimit',
  COPY_PWD: 'copyPwd',
  SHOW_LOGS: 'showLogs',
  BATCH_REMOVE: 'batchRemove',
  BATCH_REFRESH: 'batchRefresh',
  BATCH_COPY: 'batchCopy',
};
